version: "3"
services: 
    mongodb:
        image: mongo:latest
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: mergetechng
            MONGO_INITDB_ROOT_PASSWORD: 2y12kd1nZT0j.lyN3TB7uGH9uqkZpa0IzadD6SU2rq6kQ.AJmcgvo6O
            MONGO_INITDB_DATABASE: ng_jobs
        volumes: 
            - mongodb_volume:/data/db
        networks: 
            - mongodb_network
    mongodb-express:
        depends_on: 
            - mongodb
        image: mongo-express
        ports: 
            - 8082:8081
        environment: 
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            # - ME_CONFIG_MONGODB_AUTH_DATABASE=${INIT_DB_NAME}
            ME_CONFIG_MONGODB_ADMINUSERNAME: mergetechng
            ME_CONFIG_MONGODB_ADMINPASSWORD: 2y12kd1nZT0j.lyN3TB7uGH9uqkZpa0IzadD6SU2rq6kQ.AJmcgvo6O
        networks:
            - mongodb_network
volumes: 
    mongodb_volume:
networks:
    mongodb_network:
        external: true