version: "3"
services: 
    mongodb:
        image: mongodb:latest
        ports: 
            - 27017:27017
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
            MONGO_INITDB_DATABASE: ${INIT_DB_NAME}
        volumes: 
            - mongodb_volume:/data/db
        networks: 
            - mongodb_network
    mongodb-express:
        depends_on: 
            - mongodb
        image: mongodb-express
        ports: 
            - 8082:8081
        environment: 
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
            ME_CONFIG_MONGODB_ENABLE_ADMIN: true
        networks:
            - mongodb_network