package com.mergetechng.jobs.commons.enums;

public enum PrivilegesEnum {
    UPDATE_SURCHARGE,
    READ_PAYMENT,
    DELETE_PAYMENT,
    UPDATE_PAYMENT,
    READ_TRACKING,
    DELETE_TRACKING,
    UPDATE_WALLET_INFORMATION,
    VIEW_SERVER_HEALTH,
    VIEW_LOG_REQUEST,
    DELETE_LOG_REQUEST,
    VIEW_PAYMENT_RECEIPT,
    DELETE_PAYMENT_RECEIPT,
    USER_DASHBOARD,
    USER_TRIP,
    EDIT_PROFILE,
    CHANGE_PROFILE,
    DELETE_ACCOUNT,

}
